original_key = b'For_Super_Earth!'
received_key = b'For_Super_Ea????' # This key was used to cipher message
known_key = b'For_Super_Ea'
ciphertext_hex = "ba7940fae82e89774bf65b29df60b8912e6303f2820bf06db0614a67ac9930a33355a2d1163dc5e3879732c9ed6aeaabfb410bc479246175b36a59d66f9eb1a7"
target = b"PJATK{" # Ministry of truth confirms that this is prefix of message
